export enum OnwardQuestionUniqueNames {
  mailingCountryEditProfile = 'Mailing_Country_',
  university = 'Education_University_Name',
  state = 'State/Province',
  studyArea = 'Education_Primary_area_Study',
  educationLevel = 'Education_Are_currently_student',
  firstPriorityWithWhomWantToGo = 'First_Priority_With_Whom_Want_to_Go',
  hasLivingParent1 = 'Living_parent',
  hasLivingParent2 = 'ParentsListSecondParent',
  hasLivingGuardian = 'guardian_living',
  requireEpiPen = 'Medical_Epi_Pen',
  emergencyContact = 'emergency_contact',

  parent1Email = 'parent_1_email',
  parent1Phone = 'parent_1_phone',
  parent1FirstName = 'Parent1_First_Name',
  parent1LastName = 'Parent1_Last_Name',
  parent1Address = 'Parent1_Address',
  parent1Country = 'parent_1_country',

  parent2Email = 'parent_2_email',
  parent2Phone = 'parent_2_phone',
  parent2FirstName = 'Parent2_First_Name',
  parent2LastName = 'Parent2_Last_Name',
  parent2Address = 'Parent2_Address',
  parent2Country = 'parent_2_country',

  guardianEmail = 'Guardian_email',
  guardianPhone = 'Guardian_Phone',
  guardianFirstName = 'Guardian_First_Name',
  guardianLastName = 'Guardian_Last_Name',
  guardianAddress = 'Guardian_Address',
  guardianCountry = 'guardian_country',

  emergencyEmail = 'emergency_email',
  emergencyPhone = 'emergency_phone',
  emergencyName = 'EmergencyContactName',
}
